DELETE FROM PLAYER
WHERE
	ID = '9W2yEWc2B8yE';

DELETE FROM PLAYER
WHERE
	ID = 'qaCrtP1_C5qe';

DELETE FROM PLAYER
WHERE
	ID = '2mHgm-6Jzwt4';

DELETE FROM PLAYER
WHERE
	ID = 'dnFoiSQXqwAR';

DELETE FROM PLAYER
WHERE
	ID = 'ORZAsZ5MlE6c';

ALTER TABLE PLAYER
ALTER COLUMN EMAIL
SET NOT NULL;

ALTER TABLE PLAYER
ALTER COLUMN PASSWORD_HASH
SET NOT NULL;

ALTER TABLE GAME
DROP COLUMN WHITE_ID;

ALTER TABLE GAME
DROP COLUMN BLACK_ID;
CREATE TABLE IF NOT EXISTS RATED_GAME (
	GAME_ID CHAR(12) UNIQUE NOT NULL REFERENCES GAME (ID) ON DELETE CASCADE,
	WHITE_ID CHAR(12) REFERENCES PLAYER (ID) ON DELETE CASCADE,
	BLACK_ID CHAR(12) REFERENCES PLAYER (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ENGINE_GAME (
	GAME_ID CHAR(12) UNIQUE NOT NULL REFERENCES GAME (ID) ON DELETE CASCADE,
	PLAYER_ID CHAR(12) REFERENCES PLAYER (ID) ON DELETE CASCADE,
	PLAYER_COLOR SMALLINT NOT NULL,
	DIFFICULTY SMALLINT NOT NULL
);