CREATE TABLE IF NOT EXISTS player (
	id CHAR(12) BINARY PRIMARY KEY,
	name VARCHAR(60) NOT NULL UNIQUE,
	rating FLOAT NOT NULL DEFAULT 1500,
	rating_deviation FLOAT NOT NULL DEFAULT 350.0,
	rating_volatility FLOAT NOT NULL DEFAULT 0.06,
	email VARCHAR(100) NOT NULL UNIQUE,
	password_hash BINARY(60) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);