ALTER TABLE PLAYER
ALTER COLUMN EMAIL
DROP NOT NULL;

ALTER TABLE PLAYER
ALTER COLUMN PASSWORD_HASH
DROP NOT NULL;

INSERT INTO
	PLAYER (ID, NAME)
VALUES
	('9W2yEWc2B8yE', 'Easy Stockfish');

INSERT INTO
	PLAYER (ID, NAME)
VALUES
	('qaCrtP1_C5qe', 'Medium Stockfish');

INSERT INTO
	PLAYER (ID, NAME)
VALUES
	('2mHgm-6Jzwt4', 'Hard Stockfish');

INSERT INTO
	PLAYER (ID, NAME)
VALUES
	('dnFoiSQXqwAR', 'Insane Stockfish');

INSERT INTO
	PLAYER (ID, NAME)
VALUES
	('ORZAsZ5MlE6c', 'Impossible Stockfish');

ALTER TABLE GAME
ADD COLUMN WHITE_ID CHAR(12) REFERENCES PLAYER (ID) ON DELETE CASCADE;

ALTER TABLE GAME
ADD COLUMN BLACK_ID CHAR(12) REFERENCES PLAYER (ID) ON DELETE CASCADE;

DROP TABLE IF EXISTS RATED_GAME;

DROP TABLE IF EXISTS ENGINE_GAME;