CREATE TABLE IF NOT EXISTS signup_token (
	id CHAR(32) BINARY PRIMARY KEY,
	name VARCHAR(60) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	password_hash BINARY(60) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);