CREATE TABLE IF NOT EXISTS signup_token (
	id CHAR(32) BINARY PRIMARY KEY,
	player_id CHAR(12) BINARY NOT NULL,
	is_activated BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);