CREATE TABLE IF NOT EXISTS session (
	id CHAR(32) BINARY PRIMARY KEY,
	player_id CHAR(12) BINARY NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at DATETIME AS (created_at + INTERVAL 720 HOUR) STORED,
	FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);