CREATE TABLE IF NOT EXISTS player (
	id CHAR(12) PRIMARY KEY,
	name VARCHAR(60) UNIQUE NOT NULL,
	rating FLOAT NOT NULL DEFAULT 1500.0,
	rating_deviation FLOAT NOT NULL DEFAULT 350.0,
	rating_volatility FLOAT NOT NULL DEFAULT 0.06,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	is_guest BOOLEAN NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session (
	id CHAR(32) PRIMARY KEY,
	player_id CHAR(12) REFERENCES player(id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS signup_token (
	id CHAR(32) PRIMARY KEY,
	name VARCHAR(60) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_token (
	id CHAR(32) PRIMARY KEY,
	player_id CHAR(12) UNIQUE NOT NULL REFERENCES player(id) ON DELETE CASCADE,
	new_password_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game (
	id CHAR(12) PRIMARY KEY,
	moves BYTEA,
	moves_length INT NOT NULL DEFAULT 0,
	result SMALLINT NOT NULL DEFAULT 0,
	termination SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT game_chk_1 CHECK (result IN (0, 1, 2, 3)),
	CONSTRAINT game_chk_2 CHECK (termination IN (0, 1, 2, 3, 4, 5, 6, 7))
);

CREATE TABLE IF NOT EXISTS rated_game (
	game_id CHAR(12) UNIQUE NOT NULL REFERENCES game(id) ON DELETE CASCADE,
	white_id CHAR(12) NOT NULL REFERENCES player(id) ON DELETE CASCADE,
	black_id CHAR(12) NOT NULL REFERENCES player(id) ON DELETE CASCADE,
	time_control SMALLINT NOT NULL,
	time_bonus SMALLINT NOT NULL,
	time_differences BYTEA
);

CREATE TABLE IF NOT EXISTS engine_game (
	game_id CHAR(12) UNIQUE NOT NULL REFERENCES game(id) ON DELETE CASCADE,
	player_id CHAR(12) NOT NULL REFERENCES player(id) ON DELETE CASCADE,
	player_color SMALLINT NOT NULL,
	difficulty SMALLINT NOT NULL,
	CONSTRAINT engine_game_chk_1 CHECK (player_color IN (0, 1)),
	CONSTRAINT engine_game_chk_2 CHECK (difficulty IN (1, 2, 3, 4, 5))
);
