CREATE TABLE IF NOT EXISTS session (
	id CHAR(32) PRIMARY KEY,
	player_id CHAR(12) REFERENCES player(id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE player ADD COLUMN is_guest BOOLEAN NOT NULL;

ALTER TABLE rated_game ALTER COLUMN white_id SET NOT NULL;
ALTER TABLE rated_game ALTER COLUMN black_id SET NOT NULL;
ALTER TABLE engine_game ALTER COLUMN player_id SET NOT NULL;