# Required to load pg_cron background worker on start-up.
shared_preload_libraries = 'pg_cron'

# Specify the database in which the pg_cron background worker should run.
cron.database_name = 'justchess'

timezone = 'UTC'